Utility Payment App
mengiefen/utility-app pull request #2
Opened 2022-06-30 17:39 UTC by mengiefen

**In this project, a Ruby on Rails application is implemented and has the following features:**

The application allows users to:
 
- register and log in, so that the data is private to them.
- introduce new transactions associated with a category(utility).
- see the money spent on each category of transactions.
- The styling is done to match the given design
- The unit and integration tests were performed using Capybara, RSpec, FactoryBot
- The app is designed to keep the responsiveness, therefore can be seamlessly opened and used by users with mobile and desktop devices.

##  Running the app locally
  - Open terminal
  - Change to the desired directory then run the following:

    - run `git@github.com:mengiefen/utility-app.git`
    - cd utility-app/ 
    - git switch dev
    - run `bin/setup`
    - run `bin/dev`   
   
## Unit and Integration Test

- run `rails rspec` on the root directory 

## Presentation Link
https://www.loom.com/share/f51570fde4e045dbb9e4515081128c23

**Note: The linter check was giving me the following error when I check it locally. It seems that the `@include, @if, and @mixin` are not known by the stylint.  To solve this problem, I added  `"at-rule-no-unknown": null,` on the `.stylintrc.json` file.**

![image](https://user-images.githubusercontent.com/39188456/176758088-980b9f85-ad37-4aaf-965f-e73c1d621c06.png)

2022-06-30 21:27 UTC, MahmoudBakr23 requested changes
Hello @mengiefen 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Well done setting up the controllers
- Great work adding the associations and the validations to your models
- Well done setting up the routes
- Great work taking care of the credentials info of your app
- Nice presentation
- Great test suits
- Descriptive PR and commit messages
- Well done deploying your app
- Nice design

However, there is always room for improvement.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️
_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- Please fix the MIT link for a completely professional README file

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 21:27 UTC, MahmoudBakr23 commented on config/database.yml
> +  password: <%= ENV["POSTGRES_PASSWORD"] %>
**Highlight**
- Well done putting the username and the password this way 💯

2022-06-30 21:27 UTC, MahmoudBakr23 commented on app/views/payments/new.html.erb
> +    <%= f.collection_select :utility_id, Utility.all.order(:name), :id, :name, class:'select__input' %>
- [ ] Well done so far setting up the models' association and using has-many-through relationship. However, in the views form doesn't have the ability to choose more than one utility (group) to assign the transaction (payment) to. Please work on this by modifying the form to accept this feature 🙏

2022-06-30 21:27 UTC, MahmoudBakr23 commented on app/views/utilities/new.html.erb
> +        <i class="fa-solid fa-upload"></i>  Upload
- [ ] Let's work on the upload feature in this form because it doesn't accept uploaded media on the live demo link 🙏

2022-07-01 17:21 UTC, andersonlebon approved these changes
## Hi @mengiefen 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-01 18:00 UTC, merged